baseURL = "https://imrichnagy.dev/"
languageCode = "en-us"
title = "Imrich Nagy"
theme = "PaperMod"
pagerSize = 10

[params]
	author = "Imrich Nagy"
	defaultTheme = "dark"  # auto | dark | light
	showReadingTime = true
	showCodeCopyButtons = true

[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		weight = 1

	[[menu.main]]
		name = "Blog"
		url = "/blog/"
		weight = 2

	[[menu.main]]
		name = "Gallery"
		url = "/gallery/"
		weight = 3

	[[menu.main]]
		name = "Contact"
		url = "/contact/"
		weight = 4

[params.profileMode]
	enabled = true
	title = "Imrich Nagy"
	subtitle = "Software engineer, patient gamer, hyperfixation enthusiast"
	imageUrl = "images/avatar.jpg"  # Put in static/images/
	buttons = [
		{ name = "Blog", url = "/blog/" },
		{ name = "Gallery", url = "/gallery/" },
		{ name = "Download CV", url = "/files/CV_Imrich_Nagy.pdf" }
	]


[[params.socialIcons]]
	name = "github"
	url = "https://github.com/NimRo97"

[[params.socialIcons]]
	name = "linkedin"
	url = "https://linkedin.com/in/nagy-imrich"

[[params.socialIcons]]
	name = "email"
	url = "mailto:nagy@imrich.dev"

